---
deployment:
  tasks:
    - export DEPLOYPATH=/home/mattxubd/public_html/
    - /bin/cp -R webpages $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R cgi-bin $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
